const Api = {
  SkAutoCanvasRestore : 'Canvas save stack manager',
  SkBitmap : 'two:dimensional raster pixel array',
  SkBlendMode : 'pixel color arithmetic',
  SkCanvas : 'drawing context',
  SkColor : 'color encoding using integer numbers',
  SkFont : 'text style and typeface',
  SkImage : 'two dimensional array of pixels to draw',
  SkImageInfo : 'pixel dimensions and characteristic',
  SkIPoint : 'two integer coordinates',
  SkIRect : 'integer rectangle',
  SkMatrix : '3x3 transformation matrix',
  SkPaint :' color, stroke, font, effects',
  SkPath : 'a path encapsulates compound (multiple contour) geometric paths consisting of straight line segments, quadratic curves, and cubic curves',
  SkPicture : 'sequence of drawing commands',
  SkPixmap : 'pixel map: image info and pixel address',
  SkPoint : 'two floating point coordinates',
  SkRRect : 'floating point rounded rectangle',
  SkRect : 'floating point rectangle',
  SkRegion : 'compressed clipping mask',
  SkSurface : 'drawing destination',
}